/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obligatorio;
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistros = new javax.swing.JMenu();
        subMenuRegistrarRubro = new javax.swing.JMenuItem();
        subMenuRegistrarCapataz = new javax.swing.JMenuItem();
        subMenuRegistroPropietario = new javax.swing.JMenuItem();
        subMenuRegistroObra = new javax.swing.JMenuItem();
        menuGastos = new javax.swing.JMenu();
        subMenuRegistroGasto = new javax.swing.JMenuItem();
        subMenuPagoGasto = new javax.swing.JMenuItem();
        subMenuEstadoObra = new javax.swing.JMenuItem();
        menuImpYExp = new javax.swing.JMenu();
        subMenuImportacionDatosObra = new javax.swing.JMenuItem();
        subMenuExportacionDatos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Pequeñas Obras - Realizado por Nicolas Remigio e Ignacio Vidal");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(800, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        menuRegistros.setText("Registros");

        subMenuRegistrarRubro.setText("Registrar/modificar rubro");
        menuRegistros.add(subMenuRegistrarRubro);

        subMenuRegistrarCapataz.setText("Registrar capataz");
        subMenuRegistrarCapataz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuRegistrarCapatazActionPerformed(evt);
            }
        });
        menuRegistros.add(subMenuRegistrarCapataz);

        subMenuRegistroPropietario.setText("Registro de propietario");
        menuRegistros.add(subMenuRegistroPropietario);

        subMenuRegistroObra.setText("Registro de obra");
        menuRegistros.add(subMenuRegistroObra);

        jMenuBar1.add(menuRegistros);

        menuGastos.setText("Gastos");

        subMenuRegistroGasto.setText("Registro de gasto para obra");
        menuGastos.add(subMenuRegistroGasto);

        subMenuPagoGasto.setText("Pago de gasto");
        menuGastos.add(subMenuPagoGasto);

        subMenuEstadoObra.setText("Estado de obra");
        menuGastos.add(subMenuEstadoObra);

        jMenuBar1.add(menuGastos);

        menuImpYExp.setText("Importación y Exportación");

        subMenuImportacionDatosObra.setText("Importación de datos para obra nueva");
        menuImpYExp.add(subMenuImportacionDatosObra);

        subMenuExportacionDatos.setText("Exportación de datos de Propietarios y Capataces");
        menuImpYExp.add(subMenuExportacionDatos);

        jMenuBar1.add(menuImpYExp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuRegistrarCapatazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuRegistrarCapatazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMenuRegistrarCapatazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuGastos;
    private javax.swing.JMenu menuImpYExp;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JMenuItem subMenuEstadoObra;
    private javax.swing.JMenuItem subMenuExportacionDatos;
    private javax.swing.JMenuItem subMenuImportacionDatosObra;
    private javax.swing.JMenuItem subMenuPagoGasto;
    private javax.swing.JMenuItem subMenuRegistrarCapataz;
    private javax.swing.JMenuItem subMenuRegistrarRubro;
    private javax.swing.JMenuItem subMenuRegistroGasto;
    private javax.swing.JMenuItem subMenuRegistroObra;
    private javax.swing.JMenuItem subMenuRegistroPropietario;
    // End of variables declaration//GEN-END:variables
}
