/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obligatoriodos;

import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JOptionPane;

import modelos.*;

public class RegistroObra extends javax.swing.JFrame {

    private static final Rubro Aislamiento = null;
    ArrayList<Rubro> rubrosPresupuestados;
    /**
     * Creates new form RegistroObra
     */
    Sistema sistema;

    private ArrayList<Capataz> listaCapataces;
    private ArrayList<Propietario> listaPropietarios;
    private ArrayList<Rubro> listaRubros;
    int presupuestoTotal = 0;
 

    //
    public RegistroObra(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        cargarDatosListas(sistema);
        actualizarModelos();
        actualizarPanelRubros();
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                crearObra(); // Llama al método crearObra cuando se hace clic en jButton1
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        panelRubros = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 480));
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(770, 600));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Registrar obra");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 180, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 60, 770, 10);

        jLabel1.setText("Capataces:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 80, 80, 16);

        jLabel2.setText("Propietarios:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 80, 80, 16);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 100, 170, 146);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 100, 170, 146);

        panelRubros.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(panelRubros);
        panelRubros.setBounds(40, 260, 370, 170);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("0");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(580, 290, 90, 16);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(460, 100, 90, 22);

        jLabel4.setText("Permiso nro:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 80, 100, 16);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(460, 160, 260, 22);

        jLabel6.setText("Direccion");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(460, 140, 100, 16);
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(530, 230, 90, 22);
        jPanel1.add(jSpinner2);
        jSpinner2.setBounds(460, 230, 64, 22);

        jLabel7.setText("Comienzo mes/año:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(460, 210, 170, 16);

        jLabel8.setText("Total presupuesto:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(460, 290, 110, 16);

        jButton1.setText("Agregar");
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 390, 160, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // cargamos las listas con los datos del sistema de propietarios y capataces
    private void cargarDatosListas(Sistema sistema) {
        this.listaCapataces = sistema.getCapataces();
        this.listaPropietarios = sistema.getPropietarios();
        this.listaRubros = sistema.getRubros();
    }

    private void actualizarModelos() {
        String[] capatacesArray = listaCapataces.stream()
                .map(Capataz::toString)
                .toArray(String[]::new);
        String[] propietariosArray = listaPropietarios.stream()
                .map(Propietario::toString)
                .toArray(String[]::new);
        jList1.setListData(capatacesArray);
        jList2.setListData(propietariosArray);
    }


    //
     private void actualizarPanelRubros() {
        presupuestoTotal = 0;
        panelRubros.removeAll();
        panelRubros.setLayout(new GridLayout(8, 2));
        for (Rubro rubro : listaRubros) {
            String rubroTxt;
            JButton nuevo = new JButton();
            nuevo.setMargin(new Insets(0, 0, 0, 0));
            if (rubro.getPresupuesto() > 0) {
                nuevo.setBackground(Color.BLUE);
                rubroTxt = rubro.getNombre() + " " + rubro.getPresupuesto();
                presupuestoTotal += rubro.getPresupuesto();
              
            } else {
                nuevo.setBackground(Color.BLACK);
                rubroTxt = rubro.getNombre();
            }

            nuevo.setForeground(Color.WHITE);
            nuevo.setText(rubroTxt);
            nuevo.addActionListener(new RubroListener());
            panelRubros.add(nuevo);
        }
        jLabel3.setText("" + presupuestoTotal);
        panelRubros.revalidate();
        panelRubros.repaint();

    }


     private class RubroListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            JButton cual = (JButton) e.getSource();
            String[] partes = cual.getText().split(" ");
            String nombreRubro = partes[0];

            String montoStr = JOptionPane.showInputDialog(null, "Ingrese monto para el rubro " + cual.getText(), "Monto", JOptionPane.PLAIN_MESSAGE);
            try {
                int monto = Integer.parseInt(montoStr);
                cual.setText(nombreRubro + " - " + monto);
                cual.setBackground(Color.BLUE);

                // Buscar el rubro correspondiente en el sistema y actualizar su costo
                for (Rubro rubro : sistema.getRubros()) {
                    if (rubro.getNombre().equals(nombreRubro)) {
                        rubro.setPresupuesto(monto);
                        actualizarPanelRubros();
                        break;
                    }
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }


        public void crearObra() {
        // Capturar los valores de los componentes y crear un objeto Obra
        String permiso = jTextField1.getText();
        String direccion = jTextField2.getText();
        int anio = (int) jSpinner1.getValue();
        int mes = (int) jSpinner2.getValue();

        // Capturar el propietario seleccionado
        Propietario propietarioSeleccionado = listaPropietarios.get(jList2.getSelectedIndex());

        // Capturar el capataz seleccionado
        Capataz capatazSeleccionado = listaCapataces.get(jList1.getSelectedIndex());

        System.out.println("el permiso tiene el valor " + permiso);
        System.out.println("la direccion tiene el valor " + direccion);
        System.out.println("el mes tiene el valor " + mes);
        System.out.println("el año tiene el valor " + anio);
        System.out.println("el propietario tiene el valor " + propietarioSeleccionado.getNombre());
        System.out.println("el capataz tiene el valor " + capatazSeleccionado.getNombre());

        // Crear un objeto Obra con los valores capturados
        Obra nuevaObra = new Obra(propietarioSeleccionado, capatazSeleccionado, direccion, mes, anio, presupuestoTotal,
                Integer.parseInt(permiso));

        // importante recuperar
        // Capturar los rubros seleccionados
        for(Rubro rubro : listaRubros){
            if(rubro.getPresupuesto() > 0) {
                nuevaObra.setRubrosPresupuestados(rubro);
                System.out.println("agregamos el rubro " + rubro.getNombre());                      
            }
        }
     
        sistema.setObra(nuevaObra);
        System.out.println("el presupuesto total da " + nuevaObra.getPresupuestoTotal());
        System.out.println(sistema.getObras());

    }


    //
    /**
     * @param args
     */
        public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroObra.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sistema sistema = new Sistema(); // Assumes you have a default constructor
                new RegistroObra(sistema).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panelRubros;
    // End of variables declaration//GEN-END:variables
}
