/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obligatoriodos;

import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import modelos.Gasto;
import modelos.Rubro;

/**
 *
 * @author Haha yes
 */
public class RegistroGasto extends javax.swing.JFrame {

    /**
     * Creates new form RegistroGasto
     */
    private Sistema sistema;

    public RegistroGasto(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        cargarObrasALista();
        cargarRubrosALista();
    }

    private void cargarObrasALista() {
        String empty[] = {""};
        listObrasRegistradas.setListData(empty);
        String[] arrayObras = new String[sistema.getObras().size()];
        for (int i = 0; i < sistema.getObras().size(); i++) {
            arrayObras[i] = sistema.getObras().get(i).getNumeroDePermiso() + ", " + sistema.getObras().get(i).getDireccion();
        }
        listObrasRegistradas.setListData(arrayObras);
    }

    private void cargarRubrosALista() {
        String empty[] = {""};
        listRubrosRegistrados.setListData(empty);
        String[] arrayRubros = new String[sistema.getRubros().size()];
        for (int i = 0; i < sistema.getRubros().size(); i++) {
            arrayRubros[i] = sistema.getRubros().get(i).getNombre();
        }
        listRubrosRegistrados.setListData(arrayRubros);
    }

    private Rubro devolverRubroPorNombre(String nombre) {
        Rubro rubro = new Rubro(null, null, 0);
        for (int i = 0; i < sistema.getRubros().size(); i++) {
            if (nombre.equals(sistema.getRubros().get(i).getNombre())) {
                rubro = sistema.getRubros().get(i);
            }
        }
        return rubro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listObrasRegistradas = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRubrosRegistrados = new javax.swing.JLabel();
        btnRegistrarGasto = new javax.swing.JButton();
        lblRubrosRegistrados1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listRubrosRegistrados = new javax.swing.JList<>();
        txtMonto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spnMes = new javax.swing.JSpinner();
        spnAnio = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTextField3.setText("jTextField1");

        jLabel3.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setMinimumSize(new java.awt.Dimension(690, 430));
        jPanel1.setLayout(null);

        listObrasRegistradas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listObrasRegistradas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 200, 210);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Registrar gasto");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 240, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 60, 670, 10);

        lblRubrosRegistrados.setText("Obras registradas:");
        jPanel1.add(lblRubrosRegistrados);
        lblRubrosRegistrados.setBounds(20, 80, 140, 16);

        btnRegistrarGasto.setText("Registrar");
        btnRegistrarGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarGastoMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegistrarGasto);
        btnRegistrarGasto.setBounds(290, 360, 120, 30);

        lblRubrosRegistrados1.setText("Rubros registrados:");
        jPanel1.add(lblRubrosRegistrados1);
        lblRubrosRegistrados1.setBounds(250, 80, 140, 16);

        listRubrosRegistrados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listRubrosRegistrados);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(250, 100, 140, 210);
        jPanel1.add(txtMonto);
        txtMonto.setBounds(420, 100, 110, 22);

        jLabel1.setText("Descripcion:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 200, 110, 16);

        jLabel7.setText("Año:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(490, 140, 40, 16);

        spnMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jPanel1.add(spnMes);
        spnMes.setBounds(420, 160, 64, 22);

        spnAnio.setModel(new javax.swing.SpinnerNumberModel(2024, 2024, null, 1));
        jPanel1.add(spnAnio);
        spnAnio.setBounds(490, 160, 90, 22);

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtAreaDescripcion);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(420, 220, 250, 90);

        jLabel2.setText("Monto:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 80, 50, 16);

        jLabel8.setText("Mes:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 140, 40, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarGastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarGastoMouseClicked
        if (txtMonto.getText().isEmpty() || txtAreaDescripcion.getText().isEmpty() || listObrasRegistradas.getSelectedValue() == null || listRubrosRegistrados.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos y seleccione un rubro y una obra.");
            return; // Salir del método si algún campo está vacío
        }
        for (int i = 0; i < sistema.getObras().size(); i++) {
            if (parseInt(listObrasRegistradas.getSelectedValue().split(",", 2)[0]) == (sistema.getObras().get(i).getNumeroDePermiso())) {
                int monto = parseInt(txtMonto.getText());
                int mes = (Integer) spnMes.getValue();
                int anio = (Integer) spnAnio.getValue();
                Gasto gasto = new Gasto(monto, mes, anio, txtAreaDescripcion.getText(), sistema.getObras().get(i).getGastos().size() + 1, devolverRubroPorNombre(listRubrosRegistrados.getSelectedValue()));
                sistema.getObras().get(i).setGastos(gasto);
                JOptionPane.showMessageDialog(this, "Gasto registrado a la obra con nro de permiso " + sistema.getObras().get(i).getNumeroDePermiso() + "\nNumero de gasto para esta obra: " + gasto.getNumeroDeGasto());
                txtMonto.setText("");
                txtAreaDescripcion.setText("");
            }
        }
    }//GEN-LAST:event_btnRegistrarGastoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // new RegistrarRubro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarGasto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblRubrosRegistrados;
    private javax.swing.JLabel lblRubrosRegistrados1;
    private javax.swing.JList<String> listObrasRegistradas;
    private javax.swing.JList<String> listRubrosRegistrados;
    private javax.swing.JSpinner spnAnio;
    private javax.swing.JSpinner spnMes;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
