/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obligatoriodos;

import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import modelos.Gasto;
import modelos.Obra;

/**
 *
 * @author Haha yes
 */
public class RegistrarPago extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPago
     */
    private Sistema sistema;

    public RegistrarPago(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        cargarObrasALista();
    }

    private void cargarObrasALista() {
        String empty[] = {""};
        listObrasRegistradas.setListData(empty);
        String[] arrayObras = new String[sistema.getObras().size()];
        for (int i = 0; i < sistema.getObras().size(); i++) {
            arrayObras[i] = sistema.getObras().get(i).getNumeroDePermiso() + ", " + sistema.getObras().get(i).getDireccion();
        }
        listObrasRegistradas.setListData(arrayObras);
    }

    private void cargarGastosALista(Obra obra) {
        String empty[] = {""};
        listGastosImpagos.setListData(empty);
        String[] arrayGastos = new String[obra.getGastos().size()];
        for (int i = 0; i < obra.getGastos().size(); i++) {
            if (obra.getGastos().get(i).getReintegrado() == false) {
                arrayGastos[i] = String.valueOf(obra.getGastos().get(i).getMonto() + " - Nro. " + obra.getGastos().get(i).getNumeroDeGasto() + " - " + obra.getGastos().get(i).getDescripcion());
            }
        }
        listGastosImpagos.setListData(arrayGastos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listObrasRegistradas = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRubrosRegistrados = new javax.swing.JLabel();
        lblRubrosRegistrados1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listGastosImpagos = new javax.swing.JList<>();
        btnRegistrarPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar pago");
        setMinimumSize(new java.awt.Dimension(400, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 380));
        jPanel1.setLayout(null);

        listObrasRegistradas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listObrasRegistradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listObrasRegistradasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listObrasRegistradas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 100, 130, 160);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Registrar pago");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 240, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 60, 400, 10);

        lblRubrosRegistrados.setText("Obras registradas:");
        jPanel1.add(lblRubrosRegistrados);
        lblRubrosRegistrados.setBounds(50, 80, 140, 16);

        lblRubrosRegistrados1.setText("Gastos impagos:");
        jPanel1.add(lblRubrosRegistrados1);
        lblRubrosRegistrados1.setBounds(210, 80, 140, 16);

        jScrollPane2.setViewportView(listGastosImpagos);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(210, 100, 130, 160);

        btnRegistrarPago.setText("Registrar");
        btnRegistrarPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarPagoMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegistrarPago);
        btnRegistrarPago.setBounds(140, 290, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarPagoMouseClicked
        if (listObrasRegistradas.getSelectedValue() == null || listGastosImpagos.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una obra y el gasto a pagar.");
            return; // Salir del método si algún campo está vacío
        }
        for (int i = 0; i < sistema.getObras().size(); i++) {
            if (parseInt(listObrasRegistradas.getSelectedValue().split(",", 2)[0]) == (sistema.getObras().get(i).getNumeroDePermiso())) {
                for (int j = 0; j < sistema.getObras().get(i).getGastos().size(); j++) {
                    if (sistema.getObras().get(i).getGastos().get(j).getNumeroDeGasto() == parseInt(listGastosImpagos.getSelectedValue().split("-", 3)[1].substring(6, 7)) && (sistema.getObras().get(i).getGastos().get(j).getReintegrado() == false)) {
                        sistema.getObras().get(i).getGastos().get(j).setReintegrado(true);
                        JOptionPane.showMessageDialog(this, "Pago registrado a la obra con nro de permiso " + sistema.getObras().get(i).getNumeroDePermiso());
                    }
                }
            }
        }
        String empty[] = {""};
        listGastosImpagos.setListData(empty);
        listObrasRegistradas.setSelectedValue(null, rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnRegistrarPagoMouseClicked

    private void listObrasRegistradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listObrasRegistradasMouseClicked
        for (int i = 0; i < sistema.getObras().size(); i++) {
            if (parseInt(listObrasRegistradas.getSelectedValue().split(",", 2)[0]) == (sistema.getObras().get(i).getNumeroDePermiso())) {
                cargarGastosALista(sistema.getObras().get(i));
            }
        }
    }//GEN-LAST:event_listObrasRegistradasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // new RegistrarRubro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblRubrosRegistrados;
    private javax.swing.JLabel lblRubrosRegistrados1;
    private javax.swing.JList<String> listGastosImpagos;
    private javax.swing.JList<String> listObrasRegistradas;
    // End of variables declaration//GEN-END:variables
}
