/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obligatoriodos;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelos.Propietario;

public class RegistrarPropietario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPropietario
     */
    private Sistema sistema;

    public RegistrarPropietario(Sistema sistema) {
        this.sistema = sistema;
        initComponents();

        // Limita el largo de txtCelular a 9
        txtCelular.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (txtCelular.getText().length() >= 9) {
                    e.consume();
                }
            }
        });

        // Limita el largo de txtCedula a 8
        txtCedula.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (txtCedula.getText().length() >= 8) {
                    e.consume();
                }
            }
        });

        btnRegistrarPropietario.addActionListener((ActionEvent e) -> {
            registrarPropietario();
        });
    }

    private void registrarPropietario() {
        boolean propietarioRegistrado = false;

        while (!propietarioRegistrado) {
            String nombre = txtNombre.getText();
            String cedula = txtCedula.getText();
            String direccion = txtDireccion.getText();
            String celularStr = txtCelular.getText();

            // Validar si los campos están vacíos
            if (nombre.isEmpty() || cedula.isEmpty() || direccion.isEmpty() || celularStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
                return; // Salir del método si algún campo está vacío
            }

            int celular;
            try {
                celular = Integer.parseInt(celularStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El número de celular debe ser un valor numérico.");
                return; // Salir del método si el celular no es un número válido
            }

            Propietario propietario = new Propietario(nombre, cedula, direccion, celular);
            if (sistema.validarPropietario(propietario)) {
                sistema.setPropietario(propietario);
                JOptionPane.showMessageDialog(this, "Propietario registrado con éxito!");
                System.out.println(sistema.getPropietarios());

                txtNombre.setText("");
                txtCedula.setText("");
                txtDireccion.setText("");
                txtCelular.setText("");
                propietarioRegistrado = true;
            } else {
                JOptionPane.showMessageDialog(this,
                        "El número de cédula debe ser único. Por favor, introduzca una cédula diferente.");
                txtCedula.setText("");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCedula = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCelular = new javax.swing.JLabel();
        btnRegistrarPropietario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar propietario");
        setMinimumSize(new java.awt.Dimension(400, 380));
        setResizable(false);
        getContentPane().setLayout(null);

        txtCedula.setForeground(java.awt.Color.lightGray);
        txtCedula.setText("Ej: 12345678");
        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        getContentPane().add(txtCedula);
        txtCedula.setBounds(170, 140, 170, 30);

        lblNombre.setText("Nombre completo:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(50, 96, 110, 30);

        txtNombre.setForeground(java.awt.Color.lightGray);
        txtNombre.setText("Ej: Juan Gonzalez");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(170, 100, 170, 30);

        lblCedula.setText("Numero de cedula:");
        getContentPane().add(lblCedula);
        lblCedula.setBounds(50, 136, 110, 30);

        lblDireccion.setText("Direccion:");
        getContentPane().add(lblDireccion);
        lblDireccion.setBounds(100, 176, 60, 30);

        txtDireccion.setForeground(java.awt.Color.lightGray);
        txtDireccion.setText("Ej: Cuareim 1451");
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(170, 180, 170, 30);

        txtCelular.setForeground(java.awt.Color.lightGray);
        txtCelular.setText("Ej: 123456789");
        txtCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelularFocusLost(evt);
            }
        });
        getContentPane().add(txtCelular);
        txtCelular.setBounds(170, 220, 170, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 400, 10);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Registrar propietario");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 240, 40);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 380));
        jPanel1.setLayout(null);

        lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCelular.setText("Numero de celular:");
        jPanel1.add(lblCelular);
        lblCelular.setBounds(40, 220, 110, 20);

        btnRegistrarPropietario.setText("Registrar");
        jPanel1.add(btnRegistrarPropietario);
        btnRegistrarPropietario.setBounds(130, 290, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCelularFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtCelularFocusGained
        if (txtCelular.getText().equals("Ej: 123456789")) {
            txtCelular.setText("");
            txtCelular.setForeground(Color.BLACK);
        }
    }// GEN-LAST:event_txtCelularFocusGained

    private void txtCelularFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtCelularFocusLost
        if (txtCelular.getText().isEmpty()) {
            txtCelular.setForeground(Color.LIGHT_GRAY);
            txtCelular.setText("Ej: 123456789");
        }
    }// GEN-LAST:event_txtCelularFocusLost

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtCedulaFocusLost
        if (txtCedula.getText().isEmpty()) {
            txtCedula.setForeground(Color.LIGHT_GRAY);
            txtCedula.setText("Ej: 12345678");
        }
    }// GEN-LAST:event_txtCedulaFocusLost

    private void txtCedulaFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtCedulaFocusGained
        if (txtCedula.getText().equals("Ej: 12345678")) {
            txtCedula.setText("");
            txtCedula.setForeground(Color.BLACK);
        }
    }// GEN-LAST:event_txtCedulaFocusGained

    private void txtDireccionFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtDireccionFocusGained
        if (txtDireccion.getText().equals("Ej: Cuareim 1451")) {
            txtDireccion.setText("");
            txtDireccion.setForeground(Color.BLACK);
        }
    }// GEN-LAST:event_txtDireccionFocusGained

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtDireccionFocusLost
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setForeground(Color.LIGHT_GRAY);
            txtDireccion.setText("Ej: Cuareim 1451");
        }
    }// GEN-LAST:event_txtDireccionFocusLost

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtNombreFocusGained
        if (txtNombre.getText().equals("Ej: Juan Gonzalez")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.BLACK);
        }
    }// GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtNombreFocusLost
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setForeground(Color.LIGHT_GRAY);
            txtNombre.setText("Ej: Juan Gonzalez");
        }
    }// GEN-LAST:event_txtNombreFocusLost

    /**
     * @param args the command line arguments
     */
    static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietario.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        Sistema sistema = new Sistema(); // Crear una instancia de Sistema
        java.awt.EventQueue.invokeLater(() -> {
            new RegistrarPropietario(sistema).setVisible(true); // Pasar la instancia de Sistema al constructor de
            // RegistrarPropietario
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPropietario;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
